import {
  FileText,
  Combine,
  Scissors,
  Shrink,
  ImageIcon,
  FileImage,
  RotateCw,
  Lock,
  Unlock,
  FileSpreadsheet,
  Presentation,
  Image,
  Cog,
  FileType,
  Eye,
  Music,
  VideoIcon,
  FileVolume,
  ScanText,
  Images,
  Maximize,
} from "lucide-react"

export interface Tool {
  id: string
  title: string
  description: string
  icon: typeof FileText
  href: string
  category: "pdf" | "image" | "document" | "audio" | "video" | "ocr"
  color: string
}

export const toolCategories = [
  { id: "pdf", label: "PDF Tools", icon: FileText },
  { id: "image", label: "Image Tools", icon: ImageIcon },
  { id: "document", label: "Document Tools", icon: FileType },
  { id: "audio", label: "Audio Tools", icon: Music },
  { id: "video", label: "Video Tools", icon: VideoIcon },
  { id: "ocr", label: "OCR & Others", icon: ScanText },
]

export const tools: Tool[] = [
  {
    id: "merge-pdf",
    title: "Merge PDF",
    description: "Combine multiple PDFs into one file",
    icon: Combine,
    href: "/tools/merge-pdf",
    category: "pdf",
    color: "from-red-500 to-rose-500",
  },
  {
    id: "split-pdf",
    title: "Split PDF",
    description: "Extract pages from your PDF",
    icon: Scissors,
    href: "/tools/split-pdf",
    category: "pdf",
    color: "from-orange-500 to-amber-500",
  },
  {
    id: "compress-pdf",
    title: "Compress PDF",
    description: "Reduce PDF file size significantly",
    icon: Shrink,
    href: "/tools/compress-pdf",
    category: "pdf",
    color: "from-green-500 to-emerald-500",
  },
  {
    id: "pdf-to-jpg",
    title: "PDF to JPG",
    description: "Convert PDF pages to images",
    icon: FileImage,
    href: "/tools/pdf-to-jpg",
    category: "pdf",
    color: "from-purple-500 to-violet-500",
  },
  {
    id: "jpg-to-pdf",
    title: "JPG to PDF",
    description: "Convert images to PDF document",
    icon: Image,
    href: "/tools/jpg-to-pdf",
    category: "pdf",
    color: "from-blue-500 to-cyan-500",
  },
  {
    id: "rotate-pdf",
    title: "Rotate PDF",
    description: "Rotate pages in your PDF",
    icon: RotateCw,
    href: "/tools/rotate-pdf",
    category: "pdf",
    color: "from-teal-500 to-green-500",
  },
  {
    id: "lock-pdf",
    title: "Lock PDF",
    description: "Add password protection to PDF",
    icon: Lock,
    href: "/tools/lock-pdf",
    category: "pdf",
    color: "from-slate-500 to-zinc-500",
  },
  {
    id: "unlock-pdf",
    title: "Unlock PDF",
    description: "Remove password from PDF",
    icon: Unlock,
    href: "/tools/unlock-pdf",
    category: "pdf",
    color: "from-zinc-500 to-stone-500",
  },
  {
    id: "pdf-to-word",
    title: "PDF to Word",
    description: "Convert PDF to editable DOCX",
    icon: FileText,
    href: "/tools/pdf-to-word",
    category: "pdf",
    color: "from-blue-600 to-indigo-600",
  },
  {
    id: "pdf-to-excel",
    title: "PDF to Excel",
    description: "Extract tables from PDF to XLSX",
    icon: FileSpreadsheet,
    href: "/tools/pdf-to-excel",
    category: "pdf",
    color: "from-green-600 to-lime-600",
  },
  {
    id: "pdf-to-ppt",
    title: "PDF to PPT",
    description: "Convert PDF to presentation",
    icon: Presentation,
    href: "/tools/pdf-to-ppt",
    category: "pdf",
    color: "from-orange-600 to-red-600",
  },
  {
    id: "image-converter",
    title: "Image Converter",
    description: "Convert JPG, PNG, WEBP, SVG",
    icon: ImageIcon,
    href: "/tools/image-converter",
    category: "image",
    color: "from-fuchsia-500 to-pink-500",
  },
  {
    id: "heic-converter",
    title: "HEIC Converter",
    description: "Convert HEIC to JPG or PNG",
    icon: Images,
    href: "/tools/heic-converter",
    category: "image",
    color: "from-cyan-500 to-blue-500",
  },
  {
    id: "image-compress",
    title: "Image Compress",
    description: "Reduce image file size",
    icon: Shrink,
    href: "/tools/image-compress",
    category: "image",
    color: "from-emerald-500 to-teal-500",
  },
  {
    id: "image-resize",
    title: "Image Resize",
    description: "Resize image dimensions",
    icon: Maximize,
    href: "/tools/image-resize",
    category: "image",
    color: "from-sky-500 to-indigo-500",
  },
  {
    id: "document-converter",
    title: "Document Converter",
    description: "Convert between DOCX, TXT, ODT",
    icon: FileType,
    href: "/tools/document-converter",
    category: "document",
    color: "from-amber-500 to-yellow-500",
  },
  {
    id: "document-viewer",
    title: "Document Viewer",
    description: "View documents in your browser",
    icon: Eye,
    href: "/tools/document-viewer",
    category: "document",
    color: "from-rose-500 to-pink-500",
  },
  {
    id: "audio-converter",
    title: "Audio Converter",
    description: "Convert MP3, WAV, OGG, FLAC",
    icon: Music,
    href: "/tools/audio-converter",
    category: "audio",
    color: "from-indigo-500 to-purple-500",
  },
  {
    id: "audio-extract",
    title: "Extract Audio",
    description: "Extract audio from video files",
    icon: FileVolume,
    href: "/tools/audio-extract",
    category: "audio",
    color: "from-violet-500 to-fuchsia-500",
  },
  {
    id: "video-compress",
    title: "Video Compress",
    description: "Reduce video file size",
    icon: Shrink,
    href: "/tools/video-compress",
    category: "video",
    color: "from-pink-500 to-rose-500",
  },
  {
    id: "ocr",
    title: "Text Extract (OCR)",
    description: "Extract text from image or PDF",
    icon: ScanText,
    href: "/tools/ocr",
    category: "ocr",
    color: "from-blue-500 to-violet-500",
  },
]
